### ISSUE TITLE
Add "Delete" icon 

### ISSUE THREAD

**Issue by k01dun** [TexxUkr/atlasnotes#8]
Add "Delete" icon into a record "Edit" screen.

**Comment by TexxUkr** [comment]
Introduced bottom side of the Note with Timer, Done, Delete icons which we could press.
Added delete functionality for Delete icon press there.
So now we could delete a Note record while editing it right from the noteEdit scene.
Changes will be applied without Save button on right top header pressed.
After press Delete icon note will be deleted and we return to the previous scene.
